Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
  - 'config/routes.rb'

AllCops:
  Exclude:
    - 'db/migrate/*.rb'
    - 'db/schema.rb'
